import axios from "axios";
import { useState } from "react";

const Login = () => {
    const [credentials, setCredentials] = useState({
      username: '',
      password: ''
    });

    const handleChange = (e) => {
      setCredentials({
        ...credentials,
        [e.target.name]: e.target.value
      })
    }

    const handleSubmit = async (e) =>  {
      e.preventDefault();

      try {
        const response = await axios.post('http://192.168.2.100:8080/api/authenticate,credentials',credentials);
        const {id_token} = response.data
        console.log(id_token)
        localStorage.setItem('id_token', id_token);
        // localStorage.setItem('refreshToken',)
    } catch (error) {
        console.log(error)
    }
  }

  return (
    
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <form onSubmit={handleSubmit}> 
        <input type="username" name="username" value={credentials.username} onChange={handleChange} />
        <input type="password" name="password" value={credentials.password} onChange={handleChange} />
        <button type="submit"></button>
      </form>
      
      Diamond call to action
      {/* <input value={input} onChange={e => setInput(e.target.value)} type="text" placeholder="Search me" /> */}
    </div>
  );
    }

    export default Login